---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cluster-critical
value: 15000000
globalDefault: false
description: "This priority class should be assigned pod/deployment with critical cluster functionality"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 10000000
globalDefault: false
description: "This priority class should be used for highly critical services like stateful sets, daemon sets, periodical jobs & crtical Api's"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium-priority-nonpreempting
value: 5000000
globalDefault: false
preemptionPolicy: Never
description: "This priority class should be used for most common use cases like stateless services"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority-nonpreempting
value: 1000000
globalDefault: true
preemptionPolicy: Never
description: "This priority class should be used for non critical services, which can tolerate graceful interruptions"
---
